name = "m22-stellar-buzz"
account_id = "ba55b7ae9acfb3ed152103e3497c0752"
compatibility_date = "2021-11-12"
workers_dev = true

kv_namespaces = [
  { binding = "NFTS", id = "5cb6f98f97894ac889da2bf0ec4994f4", preview_id = "8970ff1d6c0948508c4bff4ce7f7823b" }
]

main = "./.cloudflare/worker.js"

[site]
bucket = "./.cloudflare/public"

[build]
command = "pnpm run build:workers"